### ISSUE TITLE
[Website] Temporarily link to this ticket system while there are no official forums

### ISSUE THREAD

**Issue by rewb0rn** [Gamua/Adobe-Runtime-Support#111]
Could be that for legal or strategic reasons you do not want to link into this github ticket system, but if none of this is holding you back, it would be great to have a link to https://github.com/Gamua/Adobe-Runtime-Support/issues from https://airsdk.harman.com/

Could be in the headers, next to News and Download. I think this would add some dynamic content to the otherwise static page and a good starting point for asking questions.

**Comment by ajwfrost** [comment]
By co-incidence, about when you opened this ticket we also pushed an update to the website..
See https://airsdk.harman.com/support

Currently we've made the decision that, rather than setting up yet another set of forum/bug pages in parallel with Adobe's and with the 'unofficial' (but more used?) ones such as this, we're probably better off just using these. As/when Adobe's pages get retired, we'll look to take over these (hopefully with the same content still as there's a lot of useful info still in there..)

**Comment by rewb0rn** [comment]
I would think in the long term it would be beneficial to have only one official bug database and one official "forums" page, preferably hosted on your website, to avoid further fragmentation of the community. But yes this is a good step forward for the time being, thanks!
