### ISSUE TITLE
Wrong resolution with Harman splash screen (ok without it) on Feathers 4.0.0 + Starling 2.5.1 + AIR 33 build 288

### ISSUE THREAD

**Issue by rdefalco** [Gamua/Adobe-Runtime-Support#135]
Hello,
while testing various FeathersSDK configurations on device, we noticed that on a configuration made by:
Feathers 4.0.0 + Starling 2.5.1 + AIR 33 build 288
I forgot to put our "adt.lic" file, and after the Harman splashscreen the app launched using only about the lower-left 1/4 of the screen. The remaining part was flashing white/yellow.

By using the "adt.lic" all seems to work properly.

Apparently, after the Harman splashscreen and starling.start() the starling instance has a viewPort with these properties
		bottom	750 [0x2ee]	
		bottomRight	flash.geom.Point (@c2e97461)	
		height	750 [0x2ee]	
		left	0	
		right	498 [0x1f2]	
		size	flash.geom.Point (@c2e97481)	
		top	0	
		topLeft	flash.geom.Point (@c2e974a1)	
		width	498 [0x1f2]	
		x	0	
		y	0	

Without the Harman splashscreen I have different values
		bottom	2148 [0x864]	
		bottomRight	flash.geom.Point (@c4241461)	
		height	2148 [0x864]	
		left	0	
		right	1080 [0x438]	
		size	flash.geom.Point (@c4241481)	
		top	0	
		topLeft	flash.geom.Point (@c42414a1)	
		width	1080 [0x438]	
		x	0	
		y	0

**Comment by ajwfrost** [comment]
We believe that the issue can be resolved by removing the width/height values from the XML descriptor file (or setting these values to zero).

However, we are also making a change in the runtime so that the correct surface size is fed back to the AIR runtime following the delayed start-up that happens when the splash screen is displayed.

Thanks for your support in finding this one!
