### ISSUE TITLE
Problem creating .aab archive

### ISSUE THREAD

**Issue by giucer70** [Gamua/Adobe-Runtime-Support#166]
This is the .bat file content:
adt -package -target aab -storetype pkcs12 -keystore SimplyTech.p12 -storepass simplypassword Click_ARM.aab bin-release-temp/Click-app.xml -C bin-release-temp Click.swf assets -extdir ext/

and this is the output result:
C:\Prg\Adobe Flash Builder 4.6\Click>android_compile_aab
WARNING: ANE [com.myflashlab.air.extensions.dependency.androidSupport.core] has no support for Android-x64
WARNING: ANE [com.myflashlab.air.extensions.dependency.overrideAir] has no support for Android-x64
WARNING: ANE [it.simplytech.ane.scan] has no support for Android-x64
WARNING: ANE [com.myflashlab.air.extensions.pdfViewer] has no support for Android-x64
WARNING: ANE [com.ssd.ane.extensions] has no support for Android-x64
WARNING: ANE [com.myflashlab.air.extensions.permissionCheck] has no support for Android-x64
WARNING: ANE [com.myflashlab.air.extensions.dependency.androidSupport.v4] has no support for Android-x64
Bundle tool failed:Error while parsing the flags: Syntax error: flags should start with -- (Flash)

Why this error?!?!

**Comment by rewb0rn** [comment]
From the error it looks like the .ANE files have no support for the 64 bits platform on Android. All ANEs have to be updated by the maintainer to integrate 64 bits support. So you should check if updates are available or get in touch with the maintainers.

**Comment by giucer70** [comment]
I don't think so, there is the support for Android-ARM64 (I can compile without errors the apk for Android 64bit ARM processor with the command "adt -package -target apk-captive-runtime -arch armv8 ecc...").
There is not support for Android-x64 (Intel processor), I have support only for Android-x86.
But is not obbligatory for the Google Playstore upload...other thing is that the message is a Warning and not an Error....I think that the errror is after when adt call bundletool and send as parameter the simbol "-" and not the simbol "--" as you can see from the error:

Bundle tool failed:Error while parsing the flags: Syntax error: flags should start with -- (Flash)

Thanks for you reply

**Comment by ajwfrost** [comment]
Sorry, yes, that output about x64 support is just a warning. Most ANEs don't actually need to specifically include this, so we are hoping to be able to eliminate this problem anyway. Currently, if you do create an app bundle, then it just means that it wouldn't work on an x64 device because of the missing ANE files.

But the error here is:
Syntax error: flags should start with -- (Flash)
and it looks like it's really basic: we are using the "bundletool" program but are passing arguments to it, one of which will be a path. And there is a space in your path; "Flash" is the first word after the space.

So, we will add the quotation marks necessary to avoid this problem.. and I think we need to ensure that we use spaces in all our paths when we do our testing!

Thanks

**Comment by giucer70** [comment]
Ok thanks....the warning is not a problem if appear or not.

Thanks for the support

**Comment by pol2095** [comment]
Hello, I have the same problem when I have a space in the path project.
When I compile the abb file, I have an output.abb file and an other file aab8763711376072635514.aab not deleted.
Thanks

**Comment by DLGames** [comment]
Would you be kind enough to point me in the right direction for an .aab android packaging tutorial, that would be awesome, I'm trying to package a .aab myself but I'm stuck at the command line, managed somehow to package a normal apk but no luck at the .aab since I don't know how to solve the java errors. Thank you!
