### ISSUE TITLE
[Feature Request] Package ANE only for arm64 architecture

### ISSUE THREAD

**Issue by rozd** [Gamua/Adobe-Runtime-Support#190]
I need to build an ANE that exposes API of SDK from another developer to AIR. The SDK is distributed as a compiled `.framework` with `x86_64` and `arm64` architectures inside. When I'm trying to package ANE with this framework included `adt` failed with error: **Error: Apple App Store allows only universal applications. "TheSDK" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.**

As I can't ask the developer to rebuild their SDK with `armv7` support I'm wondering maybe there is a way to specify that ANE should support only 64bit devices? Especially that even with latest AIR SDK and macOS Catalina there is no way to create 32bit iOS app. 

If there is no any workaround maybe you can consider to add support such feature? 

Thanks

> **Environment:**
> AIR SDK 33.0.2.338
> macOS 10.15.1

**Comment by ajwfrost** [comment]
Hi

By default we are always packaging up IPA files with universal binaries (ARMv7 + ARM64) - unless you're running on Catalina, where we can't create the ARMv7 binary hence the IPA file will just have ARM64 for you. So yes, it makes sense to then ignore the fact that the ANE doesn't have the ARMv7 section in it..

As an initial update we could change that error into a warning, but to do this properly may mean that we need to add a new option or perhaps platform definition for ANEs.. we need to ensure that ANEs and IPAs are correctly matching, to avoid any runtime problems where the app may look for an extension that's not there..

I don't know there would be any way of working around this though, unless you're able to hack the output of the "lipo" tool somehow which is what we're using to check the format. Or I'm not sure if it's feasible to modify this framework so that it actually adds in some dummy code for the other architecture?

thanks

  Andrew

**Comment by tuarua** [comment]
The easiest way is to set min iOS Version to 11.0 in platform.xml 
eg
```
<linkerOptions>
        <option>-ios_version_min 11.0</option>
```

iOS11 won't run on armv7 devices and it's likely the framework uses iOS11+ features which is why they omitted armv7.

I do this for an ARKit ANE and it produces an arm64 only ANE.

**Comment by ajwfrost** [comment]
Oh yes! So there's a flag in the packager that only throws that error if it's _not_ iOS 11 or above. Hadn't spotted that, sorry - so yes, add that option and it should be okay.

Phew :-)

**Comment by rozd** [comment]
Hi guys, I can confirm `<option>-ios_version_min 11.0</option>` works fine 😃thanks @tuarua

**Comment by hcsuk** [comment]
@rozd if you're okay with the solution there, are you okay to close this ticket please? Thanks!

**Comment by rozd** [comment]
The workaround described in the [comment](https://github.com/Gamua/Adobe-Runtime-Support/issues/190#issuecomment-570639978) works just fine for me.
