### ISSUE TITLE
[tvOS] ServerSocket cause ReferenceError exception or application hang

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#209]
## Problem Description
Using `ServerSocket` cause `ReferenceError` exception or application hang with tvOS.
Tested with AIR 33.1.0.16 with Apple TV 4K A1842 with tvOS 13.3.

It works fine with Windows, macOS, Android and iOS.

## Steps to Reproduce
Launch code below with Apple TV and make touchpad click. It just try to trace `ServerSocket.isSupported`.

Application example with sources attached.
[server_socket_crash.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/4102766/server_socket_crash.zip)
Package command used: `adt -package -target ipa-ad-hoc -storetype pkcs12 -keystore cert.p12 -storepass storepass -keypass keypass -provisioning-profile profile.mobileprovision server_socket_crash.ipa server_socket_crash-app.xml server_socket_crash.swf`

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.net.ServerSocket;
	
	public class ServerSocketCrash extends Sprite {
		
		public function ServerSocketCrash() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			stage.addEventListener(MouseEvent.CLICK, click);
		}
		
		private function click(e:MouseEvent):void {
			//This line cause: "ReferenceError: Error #1065"
			trace("ServerSocket.isSupported", ServerSocket.isSupported);
		}
	}
}
```

**Actual Result:**
Application throw exception: `ReferenceError: Error #1065`
If you try to use ServerSocket at the application start (in main class constructor for example) then application just hang without any exceptions.

**Expected Result:**
See trace
`ServerSocket.isSupported true`
without exceptions and application hangs. ServerSocket correct work.

## Known Workarounds
none

**Comment by zwetan** [comment]
from AS3 reference
[ServerSocket](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/ServerSocket.html)
> AIR profile support: This feature is supported on all desktop operating systems, on iOS (starting with AIR 3.8), and on Android (starting with AIR 3.8). This feature is not supported on AIR for TV devices. You can test for support at run time using the ServerSocket.isSupported property. See AIR Profile Support for more information regarding API support across multiple profiles.

eg. "not supported on AIR for TV devices", there is probably good reasons for that (system resources?)

anyway the first expected behaviour should be
`ServerSocket.isSupported false` without a crash (eg. at least we can not use it)

and later Harman should investigate the implementation details
see if Android TV is closer to AIR TV
or closer to Android mobile

As a **workaround**:
```as3
import flash.system.ApplicationDomain;

var hasServerSocket:Boolean = ApplicationDomain.currentDomain.hasDefinition( "flash.net.ServerSocket" );
trace( "hasServerSocket = " + hasServerSocket );
```

**Comment by ajwfrost** [comment]
AIR for TV is a different thing, that was a product for OEMS as afaik we only have one customer still using that, it was retired some time ago. So tvOS in theory should support this (as should Android TV which is just Android..).

BTW if an error like this is thrown within the initial class constructor, then yes the application would appear to hang, but you can actually add a listener for the 'uncaught errors' which means you can pick up any such error, including VerifyError etc - best to set the listener up in a static initialiser so it gets initialised prior to the constructor.

Is this a problem in AIR 32, or is it just in our beta? We've not got the tvOS build working properly yet so this may be a problem caused by that; from an initial look at the code, we should be compiling in the AS3 definitions and the C++ implementation, so whether the error is thrown from even deeper within or whether it's a build/packaging failure, we're not yet sure..

thanks

**Comment by itlancer** [comment]
Thanks for workaround. I will recheck behavior with AIR 32 and write results.

**Comment by itlancer** [comment]
Sorry, this is my mistake here. AIR 33.1.0.16 beta for tvOS still uses namespace 32.0, not 33.1 what I tried to use here.
With AIR 33.0.2.338 it works fine. Application doesn't hangs, no such crashes and `ServerSocket.isSupported` returns true.
But with latest AIR 33.1.0.43 beta there is another issue with packaging for tvOS: https://github.com/Gamua/Adobe-Runtime-Support/issues/234
