### ISSUE TITLE
AIR 31.1.1.86 Flash Builder doesn't build iOS 

### ISSUE THREAD

**Issue by sjabberwocky** [Gamua/Adobe-Runtime-Support#291]
## Problem Description

We have a game on iOS and Android.
Historically we have three projects for iphone, ipad and android.
iphone project contains whole game, but ipad and android projects have only startup class and it's own descriptors and project configurations, those projects include other sources like on this image:
![](http://dl4.joxi.net/drive/2020/04/07/0004/1311/288031/31/c6a0c42c0b.jpg)

Flash Builder works fine with latest AIR SDK and Android platform. Our build is stable and already on Google Play.

Unfortunately, something terribly wrong with iOS platform.
When Flash Builder build iphone project it copy descriptor from `project_folder/src/descriptor.xml` to `project_folder/descriptor.xml`.
When I try to run it on AIR simulator it show me this type of error:
![](http://dl3.joxi.net/drive/2020/04/07/0004/1311/288031/31/448a8914f9.jpg)

When I try to run ipad project it works fine, but when I try to build it just freeze after some operation and never complete build.
In `bin-release-temp` folder there are some `AOTBuildOutput2715444447132017904.tmp` and `AOTBuildOutput4295652293819239832.tmp` folders with a lot of `*.a` files.
[OBJFilesList.txt](https://www.dropbox.com/s/laqw7s1ln50a9ct/OBJFilesList.txt?dl=0)

So AIR 31.1.1.86 for iOS is broken.
One of the beta of AIR 31.1 worked fine.

Our project use set of latest ANEs from distriqt (Android X update).

List of ANEs:
```
<extensions>
	<extensionID>com.distriqt.Application</extensionID>
	<extensionID>com.distriqt.ApplicationRater</extensionID>
	<extensionID>com.distriqt.Bolts</extensionID>
	<extensionID>com.distriqt.Core</extensionID>
	<extensionID>com.distriqt.CloudStorage</extensionID>
	<extensionID>com.distriqt.FacebookAPI</extensionID>
	<extensionID>com.distriqt.Firebase</extensionID>
	<extensionID>com.distriqt.firebase.Crashlytics</extensionID>
	<extensionID>com.distriqt.GameServices</extensionID>
	<extensionID>com.distriqt.InAppBilling</extensionID>
	<extensionID>com.distriqt.Notifications</extensionID>
	<extensionID>com.distriqt.PushNotifications</extensionID>
	<extensionID>com.distriqt.Share</extensionID>
</extensions>
```

**Comment by ajwfrost** [comment]
Hi

The 'initial content not found' typically means that it can't find the actual SWF file referenced in the XML descriptor file!
So it's opening e:\git\mlm\TowerDefence2\iphone\Startup-app.xml
and this will contain your SWF filename.. can you check that this SWF has been correctly generated and is sat at
e:\git\mlm\TowerDefence2\iphone\[filename.swf]?

The issue with building an iPad project is an odd one, lots of .o files there though so it may just be taking a while..? how long did you leave it?! If you're able to confirm that it works with a simple project without ANEs, and then perhaps start adding in some ANEs or other complexities, we can see what may trigger the problem; the only other thing I'd suggest checking is that you have a folder:
C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib\aot\lib\MainWindow-iPad.nib
with a couple of files in it - this should be a folder, rather than a file, with the latest SDKs..

thanks

  Andrew

**Comment by sjabberwocky** [comment]
Removed all ANEs and build started to work.
Currently I'm figuring out what of the extension broke build for me.

**Comment by sjabberwocky** [comment]
It was my stupid mistake - I forgot add new com.google.firebase.core.ane to iOS build.
