### ISSUE TITLE
Error: "compile-abc-64" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by erikjthomas** [Gamua/Adobe-Runtime-Support#298]
## Problem Description

Upgraded to Catalina. Using ADT command line package command that worked fine with Mojave. Now when packaging for iOS it fails with:

![Screen Shot 2020-04-15 at 4 23 01 PM](https://user-images.githubusercontent.com/11799440/79398374-6acc7580-7f35-11ea-81fb-94a991570395.png)

* Which AIR SDK did you use? 

Harman 33.1.1.86

* Describe the affected environment: 

AIR Mobile iOS 13.3.1

* Can you reproduce it yourself, or did you get reports from other users? 

I can reproduce it myself every time.

* Links

https://tracker.adobe.com/#/view/AIR-4198909

## Steps to Reproduce

On Catalina, with latest Harman 33.1.1.86 AIR SDK, execute ADT package command, e.g.:

`  adt -package -target ipa-ad-hoc -storetype PKCS12 -keystore $IOS_SIGN_KEY -storepass "$IOS_SIGN_PWD" -provisioning-profile $PROJECT_HOME/config/ios/$ENV.mobileprovision $OUT/$ENV.ipa $OUT/app-$ENV-ios.xml -extdir $MESSAGING_SANDBOX_HOME/ane -C $OUT $ENV.swf -C $PROJECT_HOME/launchscreens . -C $PROJECT_HOME/config/ios/icons .
`

**Comment by erikjthomas** [comment]
Packaging Android builds shows a similar message:

![Screen Shot 2020-04-15 at 4 34 23 PM](https://user-images.githubusercontent.com/11799440/79399006-fdb9df80-7f36-11ea-8b7a-a5fba4ceac2e.png)

Has Harmon ensured they are submitting AIR SDK executables to Apple for notarization?

Or is there a workaround?

**Comment by marchbold** [comment]
You need to open up security and allow the app to run manually. 

- Click cancel on the dialog
- open "Security & Privacy" and unlock to make changes
- there should be an option to "open anyway"

You'll need to do this for a few of the AIR SDK executables.

**Comment by erikjthomas** [comment]
Thanks, Michael, I got past the issues for aapt l64 and compile-abc-64 and the iOS packaging completes successfully, but the android packaging fails with this now:

Packaging MessagingSandbox Android APK with 32 bit architecture...
Writing APK to: /Users/ethomas/linqto/FlexDev/MessagingSandbox/out/inhouse/inhouse.apk
NOTE: The application has been packaged with a captive runtime.
unexpected failure: Mismatch between ADT and runtime classes
java.lang.IllegalStateException: Mismatch between ADT and runtime classes
	at com.adobe.air.apk.APKOutputStream.f(APKOutputStream.java)
	at com.adobe.air.apk.APKOutputStream.n(APKOutputStream.java)
	at com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOutputStream.java)
	at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
Failed to build android inhouse.apk!

**Comment by ajwfrost** [comment]
Hi @erikjthomas  - that error happens if the adt.jar (from the SDK's 'lib' folder) comes from a different SDK from the runtime classes that are in the SDK's 'lib/android' folder. It may indicate a problem with the SDK extraction - there was a problem caused by Apple changing the 'nib' format that folk are finding a problem when coping a new SDK over the top of an existing one (annoyingly, Apple have just reverted their format change in the most recent XCode version so we're going to face this issue again at some point in the future..!)

So if you're able to extract the SDK package again and just make sure that all of the copies worked: if you search first for "MainWindow*.nib" and delete your current versions of these, it should mean that the overwrite from the new SDK package will work.

thanks

**Comment by erikjthomas** [comment]
Thank you Andrew, yes, that's what it was.
