### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by markthomasbieber** [Gamua/Adobe-Runtime-Support#310]
## Problem Description

After upgrading from air 32 to air 33.1.1.98 I get the following error

An internal error occurred during: "Launching APP NAME" 
com/adobe/air/SDK : Unsupported major.minor version 51.0

Im using windows 10. 

I made sure to delete the old 'MainWindow.nib' and 'MainWindow-iPad.nib' files from your old SDK location prior to copying the new files. I did this in the air compiler and air sdk. 

The same app that worked with Air 32 produces this issue. 

Air simulator works fine, but when debugging to an android phone or trying to compile my apk it does this. 

Both computers of mine reproduced the same problem and i even tried various versions of java, pointing the sdk directly using methods described by others and trying both jre1.8.0_251 and jdk1.8.0_102 and jre1.8.0_102 with no luck.

**Comment by ajwfrost** [comment]
Hi

Can I clarify, this is when you're trying to launch the application on a handset? Are you using an IDE like Animate/IDEA/etc, or the command-line?

The error is indeed related to the Java version, that's implying that Java 7 code isn't able to run which implies there's a Java 6 SDK somewhere that's being used. If ADT is being called from an IDE, it might be that the IDE itself has a Java VM that's being picked up by the process? Or if this is on the command line with ADT directly, are you passing in a platform SDK option?

If you are on the command line, please confirm what you get if you just type "java -version" and also what the value of %JAVA_HOME% is..

thanks

**Comment by markthomasbieber** [comment]
Sorry i should have mentioned. 
- Im using flash builder 4.7 on windows 10 
when i run java - version i get

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by ajwfrost** [comment]
So if you're using Flash Builder, what I suspect is that Flash Builder is using it's own built-in JVM in order to call ADT. They had some insider knowledge of ADT so actually call into classes with the adt.jar file rather than just using it as a command-line application..

What you'll need to do is check in the Flash Builder's JRE folder and update this. Some instructions are at
https://blogs.adobe.com/flashplayer/2018/02/running-adobe-flash-builder-on-mac-with-java-78.html

but basically it involves:
Shut down Flash Builder (and make sure it's shut! e.g. from task manager)
Back up the existing JRE folder
`C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\jre`
(so I now have `jre_old` in that installation folder)
Extract an updated JRE (1.7 or 1.8) into that location so that you have files like:
`C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\jre\bin\java.exe`
