### ISSUE TITLE
Post publishing: Can't install application to 32-bit devices using Animate on Catalina, SDK33.1.1.98

### ISSUE THREAD

**Issue by yuyuanhua** [Gamua/Adobe-Runtime-Support#357]
AIR SDK 33.1.1.98
Enviroment: Adobe Animation CC 2017, air for iOS
Device: iPad mini (A1432)
Issue:
![1592707439640](https://user-images.githubusercontent.com/35159944/85215500-30a3a800-b3ac-11ea-8aa7-bfe192b10c89.jpg)

Application can't be installed to devices in post publishing. 
Animation shows "Publish succeed", but no APP found in iPad.

**Comment by yuyuanhua** [comment]
System environment: 
macOS Catalina Version 10.15.5
Xcode version 11.5
iOS SDK 13.5

**Comment by yuyuanhua** [comment]
this may because of the 64-bit issue. I get "Installation Error: IncorrectArchitecture" when using AIR SDK32 adt command.
Any suggestions?

**Comment by ajwfrost** [comment]
Hi

An iPad mini (A1432) is a 32-bit device so can't be targeted from a Catalina machine. Catalina doesn't allow you to run 32-bit applications (which is why AIR SDK 32 will complain, because it's trying to run the 32-bit compiler that is required to create the 'universal' applications that would work on the old and new platforms).

With AIR SDK 33, we can see that you're using Catalina and so will create an IPA file that only includes the 64-bit code. This then wouldn't work on the older iPads/iPhone that don't have a 64-bit OS.

This is just a limitation of the fact that, in order to create a 32-bit target application, we need to run a 32-bit application on the host - and that's no longer possible with Catalina.

thanks

**Comment by yuyuanhua** [comment]
@ajwfrost  Thanks for your reply. I decide to roll back to Mojave. Apps need to support the old 32-bit devices.
