### ISSUE TITLE
AIR SDK 3.1.1.190 "-ios_version_min argument is missing period as second character" error

### ISSUE THREAD

**Issue by giucer** [Gamua/Adobe-Runtime-Support#391]
Hi when I compile for IOS I receive this errors:

ld: -ios_version_min argument is missing period as second character
ld: -ios_version_min argument is missing period as second character
Compilation failed while executing : ld64

I have this setting in the xml <iPhone> section:
   			<key>MinimumOSVersion</key>
   			<string>10.0</string>

when I compiled with the 3.1.1.98 it worked....

**Comment by ajwfrost** [comment]
Hi @giucer  - so we moved from using our own version of ld64 (which didn't work with the iPhoneSimulator platforms) to using the system one..
Could you please try running "ld -v" from a terminal window and let us know what comes out? And do you know what version of XCode you're on (plus OS version details) please?

thanks

**Comment by giucer** [comment]
The Operating System is OSX 10.8 Mountain Lion, the XCode that is installed is Version 5.1.1 (5B1008) and this is the result of the command:

@(#)PROGRAM:ld  PROJECT:ld64-236.4
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 armv6m armv7m armv7em
LTO support using: LLVM version 3.4svn

**Comment by ajwfrost** [comment]
Okay yes, so that's the issue, it's too old a version of ld and doesn't have support for these later iOS versions.

I don't suppose you had tried using an earlier 33.1 version (e.g. 33.1.1.98) along with the simulator? as I would be interested to see if that had worked. The reason we took our ld64 binary out was because it was outdated and no longer worked with the iOS/iPhoneSimulator 13.x SDKs..

One option might be if you're able to get the 'ld' from a later version of XCode and try that - is that feasible? If you're unable to get hold of this, please email me at andrew.frost@harman.com and we can discuss further..

thanks

**Comment by giucer** [comment]
No I don't used the simulator and I confirm that the last version that works in OSX 10.8 without this error is the 33.1.1.98. I try to move to OSX 10.13 High Sierra and XCode 10.1. Do you think I can resolve with this? Thanks for help and support...

**Comment by ajwfrost** [comment]
I think that would resolve it yes but it's quite drastic action to take! 
Are you able to just quickly try something else:
a) back up the file `/usr/bin/ld` by renaming it to something
b) copy the file from the 33.1.1.98 folder, `lib/aot/bin/ld64/ld64` into `/usr/bin` and rename this to just `ld`
Re-try with the 33.1.1.190 SDK?

**Comment by giucer** [comment]
Thaks for the suggestion...works perfectly! I can move to new OSX release with much more calmly, I think I need to move for the future because you will no longer support some features like this. Thanks
