### ISSUE TITLE
android:networkSecurityConfig

### ISSUE THREAD

**Issue by Klug76** [Gamua/Adobe-Runtime-Support#454]
Hello!

Please help how to add "android: networkSecurityConfig" xml tag/file to android apk.

**Comment by ajwfrost** [comment]
Hi

In your application descriptor file, you should be able to set this in the 'manifest additions' part?

e.g.
```<android>
  <manifestAdditions><![CDATA[
    <manifest android:installLocation="auto">
      <application android:hardwareAccelerated="true" android:networkSecurityConfig="@xml/network_security_config"/>
```

The actual XML file needs to be added as a custom resource .. we're adding a simpler way of doing this, but currently you can either use an ANE, or you can add the resource into the SDK folders manually (`lib\android\lib\resources\app_entry\res\)

thanks

**Comment by Klug76** [comment]
Thanks for the answer!
I created file
``...\SDK_Air330-217\lib\android\lib\resources\app_entry\res\xml\network_sequrity_config.xml``
and added to the manifest ``<application android:networkSecurityConfig="@xml/network_security_config"``
but when building apk get an error
```
aapt tool failed:...\Temp\bb55792d-b7a1-48f8-af0e-8726354d8804\AndroidManifest.xml:8: error: Error: No resource found that matches the given name (at 'networkSecurityConfig' with value '@xml/network_security_config').
```
How to specify the correct name for the config file?
I also tried adding this file via custom ane. Again, it is not clear how to set the path to the config file, taking into account ane package name.

**Comment by ajwfrost** [comment]
From what I can see, that looks correct other than a mis-spelling there of the file:
...\SDK_Air330-217\lib\android\lib\resources\app_entry\res\xml\network_**sequrity**_config.xml
Was that a typo just on this forum, or is the filename actually using a 'q' rather than 'c'?

One thing you can do is to add a line into the "adt.cfg" file that's in the SDK's `lib` folder, called `DebugOut=true`. Then if you look in your home folder (`c:\users\username`) there should be an `adt.log` file that shows the command used for AAPT. From memory, if you use an ANE, it treats this in the same way and just adds the resource folder in to the command-line, but I'm not 100% sure.. so for now I'd suggest sticking with trying to add this into the app_entry subfolder.

thanks

**Comment by Klug76** [comment]
Thanks, that was a stupid typo in the name.
Now everything works fine.
