### ISSUE TITLE
UnsatisfiedLinkError crash in Android

### ISSUE THREAD

**Issue by Kelsonk** [Gamua/Adobe-Runtime-Support#536]
A user keeps reporting that they can no longer open the game and recently sent me a crash report. Not sure how widespread this is or even who to blame, but maybe someone has some more info. I've used both the 259 and 300 sdk in recent versions of the game (but recently went back to 259 due to the crash issues). I'll post his message verbatim.

--------------------
Yeah, still nothing. This version (4.6.7) just won't start. Hmm, it my be the requirements for Java have changed in the new version of the game? Or need to update some related programs?
Forgive me for my persistence. I hope I didn't tire you too much. If you can't or don't want to help me, just tell me.
 
Here's what the error-report says (maybe it will help understand what the problem is):
 
Report type: crash
Package name: air.com.snowflake.CasteClicker
Package version: 4006700
Installed by: com.android.vending
Prosess name: air.com.snowflake.CasteClicker
System app: false System
Device: ST26i
Build ID: 11.2.A.0.31
Build finferprint: Sony/ST26i_1267-9559/ST26i:4.1.2/11.2.A.0.31/07_96g:user/release-keys
Product: ST26i_1267-9559
SDK version: 16
Release: 4.1.2
Incremental version: 07_96g
Codename: REL
Board: 7x27
Event log: crash
Exception class name: java.lang.UnsatisfieldLinkError
Source file: VideoViewAIR.java
Source method: nativeSetSurfaceSize
Line number: -2
Stack trace: Network
-----------------------------

**Comment by ajwfrost** [comment]
We have a problem with very old Android versions due to a required library which seemingly doesn't work on these: see their Android version number
`Release: 4.1.2`
Officially we should change the minimum SDK level so that these devices show as no longer supported, but I would prefer that we try to resolve this properly by going back to Android 4.0 and rebuilding the necessary libraries .. but this is proving to be a bit of a challenge given how Android has moved on..
So, I'm afraid no quick fixes or workarounds, other than dropping back to a very old release for them.. late March is when the updated binary was added which caused the unsatisfied link error, before that it would crash if they tried using enhanced microphone.. so try http://airsdk.harman.com/download/33.1.1.63

**Comment by Kelsonk** [comment]
Thanks! I'll let him know.

**Comment by Gokulv617** [comment]
@ajwfrost 
Google Play mandates all apps to be updated or published should target API 29. I think from AIR 33.1.1.259, it supports API 29 as targetSDK and has libraries that supports API 29. So if I go back to AIR 331.1.63, I should have targetSDK as 28 and google wont accept it. is it okay to keep targetSDK as 29 using AIR 33.1.1.63 ? Please let us know your suggestion
