### ISSUE TITLE
Harman AIR SDK release 33.1.1.300 mxml compile error:  mxml is of an unsupported type

### ISSUE THREAD

**Issue by JoeZan77** [Gamua/Adobe-Runtime-Support#577]
We are trying to migrate our legacy application Flex/AIR application, but we receive a strange error even just by compiling a simple Hello
World application:
 
X1.mxml:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:s="library://ns.adobe.com/flex/spark"
               xmlns:mx="library://ns.adobe.com/flex/mx" width="640" height="480">
    <s:layout>
        <s:BasicLayout />
    </s:layout>
    <s:Label text="Hello World!" horizontalCenter="0" verticalCenter="0" />
</s:Application>
```
 
This is the error:
./mxmlc X1.mxml
Loading configuration: /Users/g.zanella/Downloads/AIRSDK_MacOS (1)/frameworks/flex-config.xml
 
Error: /Users/g.zanella/Downloads/AIRSDK_MacOS (1)/bin/X1.mxml is of an unsupported type: mxml
 
with the legacy Apache Flex compiler all works fine:
 
/Applications/Adobe Flash Builder 4.6/sdks/4.16.0 AIR 31/bin/mxmlc X1.mxml
Create X1.swf
 
/Users/g.zanella/Downloads/AIRSDK_MacOS (1)/bin/mxmlc X1.mxml
Generates the above error
 
 
Thanks in advance for the reply

**Comment by aritgithub** [comment]
Similar errors in my applications with **AIR SDK 33** that I have not had time to investigate but that with the legacy version (**AIR SDK 32**) compile and work correctly.

**Comment by ajwfrost** [comment]
I've had previous issues in the past (with older AIR SDKs from Adobe) and I believe it's related to the Java settings (JAVA_HOME values, path information, and installed versions of Java). But it would be good to get to the bottom of exactly what causes that output..

Note that if you are using Flex, you should be using the Flex SDK and then overlaying the AIR SDK that's specifically for Flex developers - this package shouldn't then include any compilers, so the message there I think comes from the Flex compiler but perhaps is caused by an exception happening that's due to the other SDK files..

**Comment by JanFW** [comment]
I have had this issue before, too, and it is most likely a SDK overlaying issue, as Andrew suspects.
Searching for _"mxml is of an unsupported type: mxml"_ will reveal several threads pointing to a overlay issues where the non-Flex AIR SDK was used for overlaying.
