### ISSUE TITLE
ADT is compressing all Android asset files not in res/raw when packaging. Causes issues for some native libraries

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#58]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? Hint: always try the latest version from [Adobe Labs](http://labs.adobe.com/downloads/air.html).
33.0.0.182
* Describe the affected environment: Flash vs. AIR, Android vs. iOS, all devices vs. just specific models.
Android AIR
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Yes

## Steps to Reproduce
_Although similar, this is a separate issue to HARMAN Ref AIR-138_

Some native libraries when packaged as an ANE require asset files to be packaged uncompressed, eg Firebase MLKit's Modelinterpreter uses .tflite and Natural Language uses jpeg. It is not possible to package these inside res/raw. They need to be in the root of the app so that the library picks them up.

When MLKit tries to load the tflite file it throws the following Exception:
> Caused by: com.google.firebase.ml.common.FirebaseMLException: Can not load the file from asset: mobilenet/mobilenet_quant_v2_1.0_299.tflite. Please double check your assetfile name and ensure it's not compressed. See documentation for details how touse aaptOptions to skip file compression
>         at com.google.android.gms.internal.firebase_ml.zznv.load(Unknown Source:28)

Gradle provides a way of telling aapt not to compress certain file types.
It would be great if the same ability could be added to the android section of app.xml, where a developer could add comma separated list of file extensions to not compress. 

```
// gradle's implementation
android {
    // ...
    aaptOptions {
        noCompress "tflite"  // Your model's file extension: "tflite", "lite", etc.
    }
}

```
## Known Workarounds

None

**Comment by ajwfrost** [comment]
Thanks, we'd hoped that not compressing the 'res/raw' folder would be sufficient, but if there's a need to avoid a set of file extensions too then we can look into that..

**Comment by myflashlab** [comment]
Definitely needed. I'd suggest that besides defaulting to a set of file extensions, maybe the compiler can look at what resources are being added into the app and avoid compressing them all. Because if we stick to only some certain file extensions, there might be problems in future. As the [MLKIT example](https://github.com/myflashlab/Firebase-ANE/blob/master/ml_res.zip), there are ```.emd```, ```.tfl```, ```.tflite``` or ```.pb```. Even there are folders being added as a resources and some files inside that folder...

In other terms, about not compressing resources which are manually added, whatever AIR 32 was doing can continue to work fine.

the ```res/raw``` problem has been nicely fixed already :)

**Comment by tuarua** [comment]
> whatever AIR 32 was doing can continue to work fine.
AIR 32 also has the problem.

**Comment by myflashlab** [comment]
> let the developer choose what extensions

Yeah, this is great. So the process will be dynamic and not hardcoded.

**Comment by ajwfrost** [comment]
FYI we've updated this further so that you can specify file extensions that you don't want to be compressed within the APK, regardless of which folder they're for. Will be in the main SDK release targeted for Friday 9th August.

**Comment by tuarua** [comment]
This is now working well in 33.0.1.220 using the adt.cfg settings mentioned in the release notes

**Comment by walddada** [comment]
hi 
is this modification is correct adt.cfg
`# See release notes: uncomment these lines in order to force your APK to be generated with 64-bit ARM binaries
# (needed when using an IDE such as Adobe Animate that currently only provides armv7 and x86 as the options via the UI)
DefaultArch=armv8
OverrideArch=armv8

# See release notes and https://github.com/Gamua/Adobe-Runtime-Support/issues/58
#UncompressedExtensions=emd,tfl,tflite,pb

# Default is to prefiix the package with 'air.' - to turn this off, uncomment the below line
#AddAirToAppID=false

# If you need to increase the heap available to Java when packaging an Android app, you can use the below setting
# when ADT is run from another tool. (If run from the command line, just add -Xmx=2048m or similar to the command
# line within the ADT launch script..)
#JavaXmx=2048m

# For debugging, set this to 'true' and a file "adt.log" should be generated in your user's home folder
#DebugOut=true

# To override the creation of an Android APK file, and to instead create an Android App Bundle, the below
# flag can be uncommented. Note that the bundle may end up with an "apk" file extension
CreateAndroidAppBundle=true

# When creating an Android App Bundle, this flag can be used to output the Android Studio project
# files in a subfolder of your build directory (rather than using a temporary location that gets
# cleaned up on exit).
#KeepAndroidStudioOutput=true

# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
#AndroidPlatformSDK=path_to_sdk
#iOSPlatformSDK=path_to_sdk

AndroidPlatformSDK=C:\\Users\\XXXX\\AppData\\Local\\Android\\Sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
#JAVA_HOME=path_to_JDK_installation

JAVA_HOME=C:\\Program Files\\Android\\Android Studio\\jre

# NOTE TO WINDOWS USERS: paths should be either in the form "C:\\Users\\etc", with two backslash characters, or using
# forwardslash characters instead such as "C:/Users/etc". If a single backslash is used, the config file is ignored.`

**Comment by ajwfrost** [comment]
Hi @walddada  - I can't actually work out what you mean in the above, the formatting has gone completely weird to me, but given the topic this is under....

The `UncompressedExtensions` should work when creating APK files using the earlier mechanism, but with the Gradle-based builds, it was causing #1473 which will be fixed in the next AIR SDK release...

thanks

**Comment by walddada** [comment]
thanks
first my english is not good
so I will try to send you my question

In the version 33.1.1.406 I was extracting a file and it worked perfectly on the emulator

But in 33.1.1.406 and laster, the apk file does not work on the emulator

I hope my question is understandable now

thanks

**Comment by ajwfrost** [comment]
Okay thanks - I can't see any changes around the .406 build that may have affected this. Would it be possible for you to send us two APKs, one that works from the previous release, and one that fails from the later release 406+? - and to highlight what filename/path you were using to try to access this?

thanks

**Comment by walddada** [comment]
Should I put the two files here or send them to your mail?

**Comment by walddada** [comment]
hello
this the first time can I known that last sdk version can create folder android project
so 
when I import my project to android studio and I build apk
only one armeabi-v7a can be out

this build gradle file

`plugins { id 'com.android.application' }
android {
    compileSdkVersion 31
    buildToolsVersion "31.0.0"
    defaultConfig {
        applicationId "air.com.testdebugin"
        minSdkVersion 21
        targetSdkVersion 30
        multiDexEnabled true
        versionCode 1000000
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a"
        }
    }
}
dependencies {
    implementation "androidx.multidex:multidex:2.0.1"
    implementation files('libs/AppEntry.jar')
    implementation files('libs/runtimeClasses.jar')
    implementation files('libs/FlashRuntimeExtensions.jar')
    implementation files('libs/collection-1.0.0.jar')
    implementation files('libs/com.freshplanet.ane.AirAlert.jar')
    implementation files('libs/core-1.0.0.jar')
    implementation files('libs/play-services-ads-18.3.0.jar')
    implementation files('libs/play-services-ads-base-18.3.0.jar')
    implementation files('libs/play-services-ads-identifier-17.0.0.jar')
    implementation files('libs/play-services-ads-lite-18.3.0.jar')
    implementation files('libs/play-services-basement-17.0.0.jar')
    implementation files('libs/play-services-gass-18.3.0.jar')
    implementation files('libs/play-services-measurement-base-17.1.0.jar')
    implementation files('libs/play-services-measurement-sdk-api-17.1.0.jar')
    implementation files('libs/play-services-tasks-17.0.0.jar')
    implementation files('libs/so.cuo.platform.admob.jar')
    implementation project(":androidx.core")
    implementation project(":com.google.android.gms.ads.impl")
    implementation project(":com.google.android.gms.ads")
    implementation project(":com.google.android.gms.common")
}
`

**Comment by walddada** [comment]
> plugins { id 'com.android.application' }
android {
    compileSdkVersion 31
    buildToolsVersion "31.0.0"
    defaultConfig {
        applicationId "air.com.testdebugin"
        minSdkVersion 21
        targetSdkVersion 30
        multiDexEnabled true
        versionCode 1000000
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a"
        }
    }
}
dependencies {
    implementation "androidx.multidex:multidex:2.0.1"
    implementation files('libs/AppEntry.jar')
    implementation files('libs/runtimeClasses.jar')
    implementation files('libs/FlashRuntimeExtensions.jar')
    implementation files('libs/collection-1.0.0.jar')
    implementation files('libs/com.freshplanet.ane.AirAlert.jar')
    implementation files('libs/core-1.0.0.jar')
    implementation files('libs/play-services-ads-18.3.0.jar')
    implementation files('libs/play-services-ads-base-18.3.0.jar')
    implementation files('libs/play-services-ads-identifier-17.0.0.jar')
    implementation files('libs/play-services-ads-lite-18.3.0.jar')
    implementation files('libs/play-services-basement-17.0.0.jar')
    implementation files('libs/play-services-gass-18.3.0.jar')
    implementation files('libs/play-services-measurement-base-17.1.0.jar')
    implementation files('libs/play-services-measurement-sdk-api-17.1.0.jar')
    implementation files('libs/play-services-tasks-17.0.0.jar')
    implementation files('libs/so.cuo.platform.admob.jar')
    implementation project(":androidx.core")
    implementation project(":com.google.android.gms.ads.impl")
    implementation project(":com.google.android.gms.ads")
    implementation project(":com.google.android.gms.common")
}

**Comment by ajwfrost** [comment]
If you build it for a default apk target then yes it would end up just including the ARMv7 version, due to the lines that are generated there:
```
splits {
abi {
enable true
reset()
include "armeabi-v7a"
}
}
}
```
You can either change this, to create an APK for the required platform(s), or remove this section completely to include everything.
