### ISSUE TITLE
IOErrorEvent can't retrieve error text during runtime.

### ISSUE THREAD

**Issue by balaedit** [Gamua/Adobe-Runtime-Support#778]
My AIR version is 33.1.1.444

I was on load file from the server and save it on local. During the process, If internet is not connected or any other reason file not fetched from the server, IOErrorEvent.IO_ERROR will be dispatched.

My Script of IOERROR : 
function globalErrorHandler(event: IOErrorEvent) {
     errorLog.text = event.errorID + ' :: ' + event.text;
}

During debugging process, I am getting proper text that is : 
"2032 :: [Rereiving path of the URL here]".

During runtime process, I am not getting the error text :
"2032 :: "

I am currently working on Desktop version. Not checked on Android.

**Comment by balaedit** [comment]
I also checked the Android version, same issue as I am getting in desktop version.

**Comment by balaedit** [comment]
Why not responding to my issue? Is I posted some irrelevant?

I have to toast the message if there is any error occurred with it's description.

Please Help.

**Comment by ajwfrost** [comment]
Yes, this is by design. If the application is started up in debug mode (so if you're debugging via an IDE, or using ADL directly) then you get extra information in the error output. In the release builds you don't get this; the same can be achieved by adding `-nodebug` to the ADL command-line.

A secondary question would be, should we change this behaviour .. not sure whether anyone would object to this?
But see the below documentation for the actual string for error 2032:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/runtimeErrors.html
In a debug runtime, this "Stream Error." text is changed to "Stream Error. URL: %1"
but not all paths would end up having a URL being provided here..

This might be another one where we can make the change for new apps and not for old ones? so if your SWF is build with v44 then we can add the "URL: %1" text, but if not we'll leave it as before..

thanks

**Comment by balaedit** [comment]
Thanks.

I just created the global variable for error and assigned url path to the variable before adding eventlistener of error event. So then if error handler called I retrieve that passed url from my global error variable and passed it to the toast message.

thanks @ajwfrost .
