### ISSUE TITLE
[Android] Switching Wi-Fi connection with RTMFP usage in Worker cause crash

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#96]
## Problem Description
Switching Wi-Fi connection with RTMFP usage in Worker on Android devices cause application crash.
It has been tested with many different AIR versions even with latests AIR 32.0.0.144 beta and AIR 33.0.1.228 with different Android devices. With armv7 and armv8 build targets.
Same problem in all cases.
It works fine with Windows, macOS and iOS.
Also it works fine if you use RTMFP functionality in the main thread (not Worker).

## Steps to Reproduce
Launch code below with any Android device with Wi-Fi connection. Switch (disable) Wi-Fi connection on device with quick settings menu (may be few times).
Application example with sources attached.
[rtmfp_worker_crash.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3559184/rtmfp_worker_crash.zip)

```
package  {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.net.NetConnection;
	import flash.system.Worker;
	import flash.utils.ByteArray;
	import flash.system.WorkerDomain;
	
	public class RTMFPWorkerCrash extends Sprite {
		private var _netConnection:NetConnection;
		
		public function RTMFPWorkerCrash() {
			if (Worker.current.isPrimordial) {
				addEventListener(Event.ADDED_TO_STAGE, init);
			} else {
				trace("worker");
				
				_netConnection = new NetConnection();
				_netConnection.connect("rtmfp:");
			}
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			var worker:Worker = WorkerDomain.current.createWorker(this.loaderInfo.bytes);
			worker.start();
			
			addEventListener(Event.ENTER_FRAME, enterFrame);
		}
		
		//Every frame changing color rectangle just to "see" hang/crash
		private function enterFrame(e:Event):void {
			graphics.clear();
			graphics.beginFill(uint.MAX_VALUE * Math.random());
			graphics.drawRect(0, 0, 100, 100);
			graphics.endFill();
		}
	}
}
```

**Actual Result:**
Application hangs (crash). Square in top-left corner don't change it color anymore (just to "see" hang/crash).

**Expected Result:**
Application shouldn't crash.

## Known Workarounds
none (use RTMFP in the main thread but it cause performance issues ang lags)

**Comment by ajwfrost** [comment]
Hi

I thought I'd responded here yesterday but I guess not...

One of the guys has investigated this and found the cause for the hang - basically to do with threads (workers) vs the asynchronous callback mechanism used in Android. We can adjust the code so that this uses the appropriate instance for the thread but there is a risk that we're then affecting the RTMFP behaviour within the background worker.

Given our test cases are often doing things in isolation, I wondered whether you had a real-world application that uses RTMFP in a Worker and could test out a build for us to see if our fix is suitable or whether it introduces any knock-on issues? If that's a possibility, please contact us at adobe.support@harman.com and mention this issue reference..

thanks
  Andrew

**Comment by itlancer** [comment]
Issue fixed with AIR 33.1.0.16 beta. Tested with armv7, armv8, x86 and x86_64 builds.
Waiting for production release.

**Comment by itlancer** [comment]
Cannot test this issue with latest AIR 33.1.0.50 because of this crash: https://github.com/Gamua/Adobe-Runtime-Support/issues/249

**Comment by itlancer** [comment]
It works fine wih AIR 33.1.1.190.
Thank you!
